name: Update WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 0 点更新
  workflow_dispatch:       # 支持手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: True
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: True
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_TIMELINE: False
